version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - aptos-network

networks:
  aptos-network:
    driver: bridge
