version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/app/cache
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - aptos-network

networks:
  aptos-network:
    driver: bridge
