services:
  # A Docker web service
  - type: web
    name: cultivate
    env: docker
    region: oregon
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /api/info
    envVars:
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0
      - key: APTOS_NODE_URL
        sync: false
      - key: APTOS_NETWORK
        value: mainnet
      - key: POLLING_INTERVAL
        value: 60
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
      - key: DISCORD_PREFIX
        value: "!"
      - key: XAI_API_KEY
        sync: false
      - key: XAI_API_URL
        sync: false
      - key: GROK_MODEL
        sync: false
      - key: AI_TEMPERATURE
        value: 0.7
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: DISCORD_NOTIFICATION_THRESHOLD
        value: 0.8 